// <auto-generated />
using System;
using EventHub.GraphQL.DTO;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EventHub.GraphQL.Migrations
{
    [DbContext(typeof(EventHub_DbContext))]
    partial class EventHub_DbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("EventHub.GraphQL.DTO.Event", b =>
                {
                    b.Property<Guid?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<TimeOnly?>("End")
                        .HasColumnType("time(6)");

                    b.Property<bool?>("KioskPossible")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("Pax")
                        .HasColumnType("int");

                    b.Property<TimeOnly?>("SeatingTime")
                        .HasColumnType("time(6)");

                    b.Property<DateTime?>("Start")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Title")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("EventHub.GraphQL.DTO.Inventory", b =>
                {
                    b.Property<Guid?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int?>("Department")
                        .HasColumnType("int");

                    b.Property<string>("Group")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Inventory");
                });

            modelBuilder.Entity("EventHub.GraphQL.DTO.Package", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Packages");
                });

            modelBuilder.Entity("EventInventory", b =>
                {
                    b.Property<Guid>("EventsId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("InventoryId")
                        .HasColumnType("char(36)");

                    b.HasKey("EventsId", "InventoryId");

                    b.HasIndex("InventoryId");

                    b.ToTable("EventInventory");
                });

            modelBuilder.Entity("EventPackage", b =>
                {
                    b.Property<Guid>("EventsId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("PackagesId")
                        .HasColumnType("char(36)");

                    b.HasKey("EventsId", "PackagesId");

                    b.HasIndex("PackagesId");

                    b.ToTable("EventPackage");
                });

            modelBuilder.Entity("InventoryPackage", b =>
                {
                    b.Property<Guid>("InventoryId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("PackagesId")
                        .HasColumnType("char(36)");

                    b.HasKey("InventoryId", "PackagesId");

                    b.HasIndex("PackagesId");

                    b.ToTable("InventoryPackage");
                });

            modelBuilder.Entity("EventInventory", b =>
                {
                    b.HasOne("EventHub.GraphQL.DTO.Event", null)
                        .WithMany()
                        .HasForeignKey("EventsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EventHub.GraphQL.DTO.Inventory", null)
                        .WithMany()
                        .HasForeignKey("InventoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EventPackage", b =>
                {
                    b.HasOne("EventHub.GraphQL.DTO.Event", null)
                        .WithMany()
                        .HasForeignKey("EventsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EventHub.GraphQL.DTO.Package", null)
                        .WithMany()
                        .HasForeignKey("PackagesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("InventoryPackage", b =>
                {
                    b.HasOne("EventHub.GraphQL.DTO.Inventory", null)
                        .WithMany()
                        .HasForeignKey("InventoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EventHub.GraphQL.DTO.Package", null)
                        .WithMany()
                        .HasForeignKey("PackagesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
